services:
  - type: web
    name: angel-kellogg-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    
databases:
  - name: angel-kellogg-db
    databaseName: angel_kellogg
    user: angel_admin
    plan: starter
